- name: Install Nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: Deploy custom index.html to display hostname
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0644'

- name: Ensure Nginx service is running and enabled
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true

- name: Define handler to restart haproxy
  ansible.builtin.meta:
    flush_handlers
